backend:
  #name: test-repo
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "Home"
      name: "home"
      file: "content/home.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Publish Date", name: "date", widget: "datetime" }
        - { label: "Body", name: "body", widget: "markdown"}
        - label: 'Recipes'
          name: "recipes"
          widget: list
          fields:
            - { label: "Name", name: "name", widget: "string"}
            - { label: "Instructions", name: "instructions", widget: "text"}
            - { label: "Notes", name: "notes", widget: "text"}
            - { label: "Image", name: "thumbnail", widget: "image"}
    - label: "Reviews"
      name: "reviews"
      file: "content/reviews.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Publish Date", name: "date", widget: "datetime" }
        - { label: "Body", name: "body", widget: "markdown"}
        - label: 'Reviews'
          name: "reviews"
          widget: list
          fields:
            - { label: "Name", name: "name", widget: "string"}
            - { label: "Details", name: "details", widget: "text"}
            - { label: "Image", name: "thumbnail", widget: "image"}
        
            